import type { MenuItem } from "@/lib/menuData";
import { CHAO_KIDS_SEED } from "@/lib/menu/chaoKidsSeed";
import { POPULAR_THAI_CURRIES_SEED } from "@/lib/menu/popularThaiCurriesSeed";
import { STARTERS_SOUPS_SEED } from "@/lib/menu/startersSoupsSeed";

/** Supplied restaurant menu sections not covered by the existing category bundles. */
const SUPPLIED_MENU_SEED: Omit<MenuItem, "id">[] = [
  {
    name: "Pad Prik Heng",
    description:
      "Medium. Served with complimentary jasmine rice; egg fried rice +€1. Thai stir-fry with garlic, dried chilies, and crispy vegetables. Spicy, bold, and aromatic. ⭐ Customer favourite.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Nuts", "Gluten", "Fish", "Soy", "Molluscs", "Crustaceans"],
    available: true,
    emoji: "🥘",
  },
  {
    name: "Pad Khing",
    description:
      "Served with complimentary jasmine rice; egg fried rice +€1. Stir-fried with fresh ginger, vegetables, and savoury sauce. Light, aromatic, and comforting.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Fish", "Soy", "Molluscs", "Crustaceans"],
    available: true,
    emoji: "🥘",
  },
  {
    name: "Sweet & Sour Sesame Chicken",
    description:
      "Served with complimentary jasmine rice; egg fried rice +€1. Crispy fried chicken tossed in a tangy sweet-and-sour sauce, garnished with sesame seeds. Most popular.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍗",
  },
  {
    name: "Sweet & Sour Sesame Beef",
    description:
      "Served with complimentary jasmine rice; egg fried rice +€1. Crispy fried beef tossed in a tangy sweet-and-sour sauce, garnished with sesame seeds.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🥩",
  },
  {
    name: "Hot & Chilli Crispy Beef",
    description:
      "Served with complimentary jasmine rice; egg fried rice +€1. Crispy fried beef tossed in a tangy sweet-and-sour sauce, garnished with sesame seeds.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Soy", "Sesame"],
    available: true,
    emoji: "🥩",
  },
  {
    name: "Sweet Chilli Chicken",
    description:
      "Medium. Served with complimentary jasmine rice; egg fried rice +€1. Crispy shredded chicken and stir-fried vegetables seasoned in a sweet and spicy sauce.",
    basePrice: 12.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Soy", "Sesame"],
    available: true,
    emoji: "🍗",
  },
  {
    name: "Smoky Grilled Salmon",
    description:
      "Medium. Served with complimentary jasmine rice; egg fried rice +€1. Spicy marinated grilled salmon stir-fried with shredded vegetables.",
    basePrice: 13.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Soy", "Fish"],
    available: true,
    emoji: "🐟",
  },
  {
    name: "Spicy Garlic King Prawn",
    description:
      "Medium. Served with complimentary jasmine rice; egg fried rice +€1. Spicy wok-fried king prawns stir-fried with shredded vegetables.",
    basePrice: 13.99,
    category: "Classic Thai Stir-Fries",
    availableMeats: [],
    availableSides: ["Jasmine Rice", "Egg Fried Rice"],
    availableSpiceLevels: ["Mild", "Medium", "Hot"],
    allergens: ["Gluten", "Soy", "Fish", "Crustaceans"],
    available: true,
    emoji: "🍤",
  },
  {
    name: "Pad-Thai Noodle",
    description:
      "Stir-fried rice noodles with chicken and prawns, egg, bean sprouts, and tangy tamarind sauce.",
    basePrice: 12.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Soy", "Eggs", "Peanuts", "Fish"],
    available: true,
    emoji: "🍜",
  },
  {
    name: "Singapore Noodle",
    description:
      "Hot. Egg noodles stir-fried in homemade Singapore sauce with chicken and beef.",
    basePrice: 12.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Fish", "Soy", "Eggs", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍜",
  },
  {
    name: "Chao Special Noodle",
    description:
      "Medium. Egg noodles stir-fried with chilli sauce, chicken, prawns, beef and shredded vegetables.",
    basePrice: 13.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍜",
  },
  {
    name: "Chao Special Fried Rice",
    description:
      "Medium. Jasmine rice stir-fried with chicken, beef, prawns, shredded vegetables, and fried egg in a special spicy sauce.",
    basePrice: 13.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Singapore Fried Rice",
    description:
      "Hot. Jasmine rice stir-fried in homemade Singapore sauce with chicken and beef.",
    basePrice: 12.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Fish", "Soy", "Molluscs", "Eggs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Nasi Goreng",
    description:
      "Sweet and spicy Indonesian-style fried rice with chicken, prawns, vegetables, and a hint of sweet soy sauce, served with a fried egg.",
    basePrice: 13.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Chiang Mai Fried Rice",
    description:
      "Medium. Fragrant fried rice with tender beef, cashews, shredded vegetables and a fried egg.",
    basePrice: 13.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans", "Nuts"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Vegetable Fried Rice",
    description:
      "Jasmine rice stir-fried in homemade seasoned sauce with shredded vegetables, tofu and fried egg.",
    basePrice: 12.99,
    category: "Fried rice & Noodles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Fish", "Soy", "Molluscs", "Sesame", "Crustaceans"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Vegan Korma",
    description:
      "Mild. Gluten free. A mild, creamy curry made with coconut milk, mixed vegetables, fried tofu and aromatic spices. Gently sweet and rich.",
    basePrice: 12.99,
    category: "Vegan Specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan"],
    available: true,
    emoji: "🌿",
  },
  {
    name: "Vegan Koh Samui",
    description:
      "Hot. Gluten free. Spicy Thai curry made with tomato onion sauce and coconut milk, fine beans, broccoli, red chillies, mixed peppers and fried tofu.",
    basePrice: 12.99,
    category: "Vegan Specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan"],
    available: true,
    emoji: "🌿",
  },
  {
    name: "Vegan Pad Prik Haeng Stir-Fry",
    description:
      "Medium. Thai stir-fry with garlic, dried chillies, crispy vegetables and fried tofu in Chao special vegan sauce. Spicy, bold, and aromatic.",
    basePrice: 12.99,
    category: "Vegan Specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Nuts", "Vegan"],
    available: true,
    emoji: "🌿",
  },
  {
    name: "Vegan Pad-Thai Noodle",
    description:
      "Stir-fried rice noodles with fried tofu, mushroom, carrot, leeks, bean sprouts, and tangy tamarind sauce.",
    basePrice: 12.99,
    category: "Vegan Specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Peanuts", "Vegan"],
    available: true,
    emoji: "🌿",
  },
  {
    name: "Vegan Fried Rice",
    description:
      "Jasmine rice stir-fried in Chao special vegan sauce with shredded vegetables and fried tofu.",
    basePrice: 12.99,
    category: "Vegan Specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Vegan"],
    available: true,
    emoji: "🌿",
  },
  {
    name: "Steamed Jasmine Rice",
    description: "Steamed jasmine rice.",
    basePrice: 2,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan", "Vegetarian"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Egg Fried Rice",
    description: "Egg fried rice.",
    basePrice: 2.5,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Eggs", "Vegetarian"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Chicken Fried Rice",
    description: "Chicken fried rice.",
    basePrice: 3.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Eggs"],
    available: true,
    emoji: "🍚",
  },
  {
    name: "Wok Fried Noodle",
    description: "Wok fried noodle.",
    basePrice: 3.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Molluscs"],
    available: true,
    emoji: "🍜",
  },
  {
    name: "Steamed Broccoli",
    description: "Steamed broccoli.",
    basePrice: 3.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan", "Vegetarian"],
    available: true,
    emoji: "🥦",
  },
  {
    name: "Steamed Edamame Beans",
    description: "Steamed edamame beans.",
    basePrice: 4.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Soy", "Vegan", "Vegetarian"],
    available: true,
    emoji: "🫛",
  },
  {
    name: "White Prawn Crackers",
    description: "White prawn crackers.",
    basePrice: 1.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans"],
    available: true,
    emoji: "🍘",
  },
  {
    name: "Thai Brown Prawn Crackers",
    description: "MSG-free Thai brown prawn crackers.",
    basePrice: 2.49,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans"],
    available: true,
    emoji: "🍘",
  },
  {
    name: "Chips",
    description: "Potato chips.",
    basePrice: 2.99,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan", "Vegetarian"],
    available: true,
    emoji: "🍟",
  },
  {
    name: "Sweet Potato Chips",
    description: "Sweet potato chips.",
    basePrice: 3.49,
    category: "Sides & Nibbles",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan", "Vegetarian"],
    available: true,
    emoji: "🍠",
  },
  {
    name: "Soft Drinks",
    description: "Coca-Cola, Coke Zero, Diet Coke, 7Up, 7Up Free, or Fanta.",
    basePrice: 2,
    category: "Beverages",
    availableMeats: [],
    availableSides: [],
    allergens: [],
    available: true,
    emoji: "🥤",
  },
  {
    name: "Vit-Hit Green Apple",
    description: "Vit-Hit Green Apple.",
    basePrice: 2,
    category: "Beverages",
    availableMeats: [],
    availableSides: [],
    allergens: [],
    available: true,
    emoji: "🍏",
  },
  {
    name: "Vit-Hit Mango, Passion Fruit & Orange",
    description: "Vit-Hit Mango, Passion Fruit & Orange.",
    basePrice: 2,
    category: "Beverages",
    availableMeats: [],
    availableSides: [],
    allergens: [],
    available: true,
    emoji: "🥭",
  },
  {
    name: "Vit-Hit Berry",
    description: "Vit-Hit Berry.",
    basePrice: 2,
    category: "Beverages",
    availableMeats: [],
    availableSides: [],
    allergens: [],
    available: true,
    emoji: "🫐",
  },
];

/** Complete replacement menu bundle. */
export const FULL_MENU_SEED: Omit<MenuItem, "id">[] = [
  ...STARTERS_SOUPS_SEED,
  ...CHAO_KIDS_SEED,
  ...POPULAR_THAI_CURRIES_SEED,
  ...SUPPLIED_MENU_SEED,
];
