import type { MenuItem } from "@/lib/menuData";

/** Payloads for Firestore `menu` — import from Menu Management (skips duplicate names). */
export const STARTERS_SOUPS_SEED: Omit<MenuItem, "id">[] = [
  {
    name: "Vegetable Spring Roll (V)",
    description:
      "Crispy golden fried roll filled with white cabbage, carrot and glass noodle. Served with sweet chilli sauce.",
    basePrice: 5.49,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Vegan", "Vegetarian"],
    available: true,
    emoji: "🥟",
  },
  {
    name: "Honey Chilli Tofu (V)",
    description:
      "Tofu marinated in aromatic spices, deep fried, and tossed in honey chilli sauce.",
    basePrice: 6.95,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy", "Sesame", "Vegan", "Vegetarian"],
    available: true,
    emoji: "🧈",
  },
  {
    name: "Chicken Gyoza",
    description: "Dumplings filled with vegetables and chicken. Served with soy sauce.",
    basePrice: 5.49,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Soy"],
    available: true,
    emoji: "🥟",
  },
  {
    name: "Grilled Chicken Satay",
    description:
      "Marinated chicken skewers grilled. Served with rich creamy peanut sauce.",
    basePrice: 5.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans", "Soy", "Peanuts"],
    available: true,
    emoji: "🍢",
  },
  {
    name: "Sweet Chilli Drumette",
    description:
      "⭐ Kids favourite. Deep fried battered chicken seasoned in sweet & sour sauce.",
    basePrice: 7.99,
    category: "Chao Kids specials",
    availableMeats: [],
    availableSides: [],
    allergens: ["Gluten", "Eggs", "Sesame", "Soy", "Molluscs"],
    available: true,
    emoji: "🍗",
  },
  {
    name: "Spicy Wings",
    description: "Deep fried chicken wings, served with hot sauce.",
    basePrice: 6.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Soy", "Sesame"],
    available: true,
    emoji: "🍗",
  },
  {
    name: "Calamari Rings",
    description: "Squid rings marinated in spices and coated with breadcrumbs.",
    basePrice: 5.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans", "Soy", "Gluten"],
    available: true,
    emoji: "🦑",
  },
  {
    name: "Tiffin Box for 2",
    description: "Chao’s four different starters served with dips.",
    basePrice: 11.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans", "Eggs", "Gluten", "Soy"],
    available: true,
    emoji: "🍱",
  },
  {
    name: "Ramen Chicken Noodle Soup",
    description:
      "Rich, savoury broth served with egg noodle, boiled egg, bamboo shoot & scallion.",
    basePrice: 8.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans", "Eggs", "Soy"],
    available: true,
    emoji: "🍜",
  },
  {
    name: "Tom-Yam Prawn Soup",
    description:
      "Thai famous hot and sour soup, blended with lemongrass, galangal, mushroom, lime leaves & chilli.",
    basePrice: 7.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Crustaceans", "Soy", "Fish"],
    available: true,
    emoji: "🍲",
  },
  {
    name: "Spice Bag",
    description: "Deep fried chicken & potatoes seasoned with crunchy vegetables.",
    basePrice: 7.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Eggs", "Gluten"],
    available: true,
    emoji: "🥡",
  },
  {
    name: "Vegan Bag",
    description: "Deep fried potatoes & chickpeas seasoned with crunchy vegetables.",
    basePrice: 7.99,
    category: "Starters & Soups",
    availableMeats: [],
    availableSides: [],
    allergens: ["Vegan"],
    available: true,
    emoji: "🥡",
  },
];
